name: deploy pipeline

on:
    push:
        branches:
        - master

jobs:
    simple_deploy_pipeline:
        name: simple deploy pipeline
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: install dependencies
              run: npm install
            - name: check style
              run: npm run eslint
            - name: test
              run: npm run test